### ISSUE TITLE
Scoping while reloading should cancel rescope

### ISSUE THREAD

**Issue by gvarados1** [AmperSoftware/TF-Source-2-Issues#52] opened 2022-07-11 02:12 UTC
### Describe the bug

If you fire a shot with the sniper rifle and try to toggle zoom while reloading, it won't toggle. You have to wait for the reload to finish before you can toggle zoom

### To Reproduce

1. Shoot sniper rifle
2. Toggle zoom immediately after
3. zoom doesn't toggle

### Expected behavior

zoom should toggle any time you press the zoom button

**Comment by MoonlyDays** [comment] 2022-07-12 16:00
I checked this in live, and you cannot zoom while the reload is happening. This is intended behavior on the stock Sniper Rifle, unless i'm misunderstanding the issue.

**Comment by gvarados1** [comment] 2022-07-12 17:43
The zoom bool doesn't toggle so you're forced to zoom in after reloading,
even if you try to unzoom during reload

**Comment by MoonlyDays** [comment] 2022-07-12 17:57
For now set `cl_autorezoom` convar to 0. In the future it'll be configurable in the settings menu.
Note that convar changes don't persist between game sessions for now.

**Comment by MoonlyDays** [comment] 2022-07-12 18:06
Nevermind, I watched the video without volume the first time. I see the issue now. Thank you for clarifying.

**Comment by MoonlyDays** [comment] 2022-08-14 14:11
This issue seems to be fixed now. Please retest it in the current backend upload and close the issue if you consider it to be fixed.

**Closed** 2022-08-15 12:47 UTC
Labels: bug, review
